env: "local" # dev, prod

database:
  host: "localhost"
  port: "5432"
  name: "dm-trade"
  username: "postgres"
  password: "89872010riot!"

http_server:
  host: "localhost"
  port: "8081"
  read_timeout: "5s"
  write_timeout: "10s"
  max_header_megabytes: 10

auth:
  jwt:
    access_token_ttl: "720h"
    refresh_token_ttl: "1900h"
    secret: "giwfFga9h7bShimoLxZ8pVGlKGyIzgDo7saYg5Ljkt8="
  password_salt: "yoursecretsalt"

jwt:
  access_token_ttl: "15m"
  refresh_token_ttl: "24h"
  secret: "giwfFga9h7bShimoLxZ8pVGlKGyIzgDo7saYg5Ljkt8="

kafka:
  bootstrap_servers: ["192.168.0.2:9092"]
  retry_max: 5

cache:
  redis:
    url: "redis://localhost:6379/"
    password: "89872010riot!"
    db: 0